package com.acmenxd.core.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.acmenxd.core.model.db.TestBean;

import com.acmenxd.core.db.dao.TestBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testBeanDaoConfig;

    private final TestBeanDao testBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testBeanDaoConfig = daoConfigMap.get(TestBeanDao.class).clone();
        testBeanDaoConfig.initIdentityScope(type);

        testBeanDao = new TestBeanDao(testBeanDaoConfig, this);

        registerDao(TestBean.class, testBeanDao);
    }
    
    public void clear() {
        testBeanDaoConfig.clearIdentityScope();
    }

    public TestBeanDao getTestBeanDao() {
        return testBeanDao;
    }

}
